apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment  
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello
        ports:
        - containerPort: 80
          name: web

---

kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app:  nginx
  type:  NodePort
  ports:
  - name:  web
    port:  80
    targetPort:  80
    nodePort: 31111

# ---
  
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nginx-ingress
#   labels:
#     name: nginx-ingress
# spec:
#   rules:
#   - host: myapp.com
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: nginx-service
#             port: 
#               number: 80
